services:
  - type: web
    name: localshelf-explorer
    env: python
    plan: free
    buildCommand: "python -m pip install -r requirements-local.txt && python prepare_deploy.py"
    startCommand: "python app.py"
    envVars:
      - key: HF_HUB_OFFLINE
        value: "0"
      - key: TRANSFORMERS_OFFLINE
        value: "0"
